### ISSUE TITLE
Problems with Ygopro on Mac

### ISSUE THREAD

**Issue by DeluXeKhaz** [Ygoproco/LiveanimeLinks#607]
Hi, 

Recently been experiencing some issues with Ygopro, started with crashing on opening the application then had to delete liveanimelinks folder to open it but now I can't join any game sessions. I can refresh the lobbies but I can't join any of them, when I select join the screen remains the same, I can't host either. 

Running Macbook version 10.13.6

**Comment by pyrQ** [comment]
This repository is not for tech support issues, use the #tech-support Discord channel for that.
